services:
  web:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    restart: unless-stopped
    volumes:
      - /usr/share/karakeep/data:/data
    ports:
      - 3010:3000
    environment:
      - MEILI_ADDR
      - BROWSER_WEB_URL
      - KARAKEEP_VERSION
      - NEXTAUTH_SECRET
      - MEILI_MASTER_KEY
      - NEXTAUTH_URL
      - OPENAI_API_KEY
      - DATA_DIR
  chrome:
    image: ghcr.io/karakeep-app/karakeep-chrome:release
    restart: unless-stopped
    init: true
    command:
      - --disable-gpu
      - --disable-dev-shm-usage
      - --hide-scrollbars
      - --disable-blink-features=AutomationControlled
      - --window-size=1440,900
  meilisearch:
    image: getmeili/meilisearch:v1.41.0
    restart: unless-stopped
    environment:
      - MEILI_NO_ANALYTICS
      - MEILI_MASTER_KEY
    volumes:
      - /usr/share/karakeep/meilisearch:/meili_data

volumes:
  meilisearch:
  data:
